### ISSUE TITLE
Typo on Alpine 3.3 motd

### ISSUE THREAD

**Issue by rgarrigue** [maier/packer-templates#2]
Hi @maier 

Here's a small typo that got me confused for less than a minute

```
PS D:\vagrant\alpine_3.3> vagrant ssh

Alpine 3.2.3 Development Environment   <================3.2

Built for use with Vagrant using:
   <https://github.com/maier/packer-templates>

See the Alpine Wiki for how-to guides and
general information about administrating
Alpine systems and development.
See <http://wiki.alpinelinux.org>

alpine-331:~$ cat /etc/issue
Welcome to Alpine Linux 3.3
Kernel \r on an \m (\l)
```

Anyway I mostly wanted to say thank you for the nice little things around your repos :+1: 

Cheers,

**Comment by maier** [comment]
Hi @rgarrigue 

I can't actually change it now. the 3.3.1 ISO actually installs 3.3.3. Because of this, I'm switching to placing point releases in the box versions. So, today I built maier/alpine-3.3-x86_64 v1.3.0 the vagrant box version is 1.3.0, the Alpine Linux version is 3.3.3. When/if Alpine Linux 3.3.4 is released, I will cut a new vagrant box that will be version 1.4.0. Any changes I need to make to my packer config or provisioning scripts will be reflected in the patch level of the vagrant box version. (e.g. 1.3.1 would mean I changed the packer configuration which builds the Alpine v3.3.3 box.)

Sorry for the typo and the ensuing confusion.

I'm glad you find the repo useful, enjoy.
